### ISSUE TITLE
metabug: kill minidump-analyzer

### ISSUE THREAD

**Issue by Gankra** [rust-minidump/rust-minidump#654]
The final boss for this project is mozilla's [minidump-analyzer](https://searchfox.org/mozilla-central/source/toolkit/crashreporter/minidump-analyzer), which is used during crash *pings* **on the user's crashing machine** to get a quick backtrace using native debuginfo for things like drivers.

This requires looking at the paths in the minidump, and handling native debuginfo. I don't know if it has additional smarts to query for symbols using http or system services, or if it's purely using the in-minidump paths.

#647 hackily pushes us closer to this vision by adding a mode where we use minidump paths and feed them into dump_syms. This is currently *incredibly* heavy-weight, and needs a bunch of optimization.

One of the heaviest parts of the process is the fact that we process/index the entire code/debugfile even though there's maybe only a dozen entries we care about. I've been informed that for some things like function names this is kind of unavoidable, as there is no index in DWARF. CFI is however fully indexed because it needs to be *kind of* responsive. I don't know how well-indexed PE32+ is (to say nothing of PE32).

* [ ] add a --use-minidump-paths mode
* [ ] decouple http from --use-minidump-paths? (make the "http" symbolizer just a "fancy" symbolizer; make http cfg-offable without disabling the other machinery)
* [ ] ...cut out the middleman and use dump_syms' in-memory data structures directly?
* [ ] ...cut out the middleman and use symbolic directly? how much work does dump_syms do for us now?

* [ ] ...lazily parse the native binaries for only the info we need?
  * [ ] DWARF
    * [ ] CFI?
      * [ ] DWARF CFI 
      * [ ] Apple compact
    * [ ] function names / line info? **(impossible?)**
  * [ ] PE32+
    * [ ] CFI?
    * [ ] function names / line info? 
  * [ ] PE32
    * [ ] CFI?
    * [ ] function names / line info?
